# Generated by Django 2.2 on 2021-10-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_table_no',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
