# Generated by Django 2.2 on 2021-10-09 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_userdetails_user_table_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('order', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time_of_order', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('delivered', models.BooleanField()),
            ],
        ),
    ]
