# Generated by Django 2.2 on 2021-10-23 07:44

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_getuserreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='order',
            field=jsonfield.fields.JSONField(),
        ),
    ]
