# Generated by Django 2.2 on 2021-10-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211023_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='delivered',
        ),
        migrations.AddField(
            model_name='userorder',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userorder',
            name='table_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
