# Generated by Django 2.2 on 2021-10-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_addsview'),
    ]

    operations = [
        migrations.AddField(
            model_name='getuserreview',
            name='table_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='getuserreview',
            name='username',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
